/**
 * @file route.ts
 * @description API route for emailing PDF blueprint to user via Resend.
 * @author Charley Scholz, JLIT
 * @coauthor Claude Opus 4.6, Claude Code (coding assistant), Cursor (IDE)
 * @created 2026-02-11
 * @updated 2026-02-11
 */

import { NextResponse } from "next/server";
import { Resend } from "resend";

const RESEND_API_KEY = process.env.RESEND_API_KEY;

export async function POST(request: Request): Promise<Response> {
  try {
    if (!RESEND_API_KEY) {
      return NextResponse.json(
        { error: "Email service not configured. Set RESEND_API_KEY in .env.local." },
        { status: 503 }
      );
    }

    const body = await request.json();
    const { to, brandName, pdfBase64 } = body as {
      to: string;
      brandName: string;
      pdfBase64: string;
    };

    // Validate inputs
    if (!to || typeof to !== "string") {
      return NextResponse.json({ error: "Email address is required" }, { status: 400 });
    }
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(to)) {
      return NextResponse.json({ error: "Invalid email address" }, { status: 400 });
    }
    if (!pdfBase64 || typeof pdfBase64 !== "string") {
      return NextResponse.json({ error: "PDF data is required" }, { status: 400 });
    }
    if (!brandName || typeof brandName !== "string") {
      return NextResponse.json({ error: "Brand name is required" }, { status: 400 });
    }

    // Extract base64 content (strip data URI prefix if present)
    const base64Content = pdfBase64.includes(",")
      ? pdfBase64.split(",")[1]
      : pdfBase64;

    const resend = new Resend(RESEND_API_KEY);

    const filename = `${brandName.toLowerCase().replace(/\s+/g, "-")}-participation-blueprint.pdf`;

    const { data, error } = await resend.emails.send({
      from: "Participation Translator <noreply@resend.dev>",
      to: [to],
      subject: `Your Participation Blueprint — ${brandName}`,
      html: `
        <div style="font-family: Helvetica Neue, Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 40px 20px;">
          <h1 style="font-size: 24px; font-weight: 700; color: #111111; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px;">
            ${brandName}
          </h1>
          <div style="width: 60px; height: 3px; background: #166AD8; margin-bottom: 24px;"></div>
          <h2 style="font-size: 16px; font-weight: 400; color: #111111; margin-bottom: 24px;">
            Participation Blueprint
          </h2>
          <p style="font-size: 14px; color: #555555; line-height: 1.6; margin-bottom: 24px;">
            Your participation blueprint is attached as a PDF. This document contains the complete strategic narrative, 
            executional recommendations, and participation pack generated by The Participation Translator.
          </p>
          <p style="font-size: 14px; color: #555555; line-height: 1.6; margin-bottom: 32px;">
            <strong>Sections included:</strong><br/>
            • Strategic Narrative (Write-Up, Creative Approach, Media & Creator Strategy)<br/>
            • Executional Recommendations<br/>
            • Participation Pack (Big Audacious Act, Subculture Mini-Briefs, Mechanic Deep-Dives, Casting & Creators, 72-Hour Trend Hijacks)
          </p>
          <hr style="border: none; border-top: 1px solid #E5E5E5; margin: 32px 0;" />
          <p style="font-size: 11px; color: #999999; text-transform: uppercase; letter-spacing: 0.1em;">
            Generated by The Participation Translator · Strategic Intelligence
          </p>
        </div>
      `,
      attachments: [
        {
          filename,
          content: base64Content,
        },
      ],
    });

    if (error) {
      console.error("Resend error:", error);
      return NextResponse.json(
        { error: `Failed to send email: ${error.message}` },
        { status: 500 }
      );
    }

    return NextResponse.json({
      success: true,
      messageId: data?.id,
      to,
    });
  } catch (error) {
    console.error("Email route error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Failed to send email" },
      { status: 500 }
    );
  }
}
